# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69893b89eb20225d21b99e144547ab89271d8f8962dd6f048dc52bd99c5c4aa9c65ec43119a269e18bd0db6f658da873abb7ec3a21192d248473643511f6b75b
  yt_api_key: AIzaSyCl26WFnwXMi7u-F7oqbzEd3o6O-Lfe6BY
  yt_client_secret: B2qwKyO9IWuDyAVypJhcCZlD
  yt_client_id: 585436892114-o3p6edhd2op4c0buvnr2bkms67tjarvp.apps.googleusercontent.com
  fb_app_id: 987767167967724
  fb_secret: ffa59df344e6613926a88908ebd25ce9
  algolia_api_key: d28181c6c1481de88e05af66c1b423df
  algolia_app_id: J7PGJUEF2D

test:
  secret_key_base: 7456ec6c26324fe2538d65f939f1ae6a714cda711f4f153b145fb1f53d731c19575a26114536375360fa44a4a52a7c357a59525d28fe1acdbdd64287cb0b46d9
  yt_api_key: AIzaSyCl26WFnwXMi7u-F7oqbzEd3o6O-Lfe6BY
  yt_client_secret: B2qwKyO9IWuDyAVypJhcCZlD
  yt_client_id: 585436892114-o3p6edhd2op4c0buvnr2bkms67tjarvp.apps.googleusercontent.com
  fb_app_id: 987767167967724
  fb_secret: ffa59df344e6613926a88908ebd25ce9
  algolia_api_key: d28181c6c1481de88e05af66c1b423df
  algolia_app_id: J7PGJUEF2D

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: bef846d01af35580d1588acc9c11187bc01f7ff77619b5695c3a59ac6f4068177ee76d7f34f62a306dba9947632a29b8291ece01870f652420780c1b8827579b
  yt_api_key: AIzaSyCl26WFnwXMi7u-F7oqbzEd3o6O-Lfe6BY
  yt_client_secret: B2qwKyO9IWuDyAVypJhcCZlD
  yt_client_id: 585436892114-o3p6edhd2op4c0buvnr2bkms67tjarvp.apps.googleusercontent.com
  fb_app_id: 987767167967724
  fb_secret: ffa59df344e6613926a88908ebd25ce9
  algolia_api_key: d28181c6c1481de88e05af66c1b423df
  algolia_app_id: J7PGJUEF2D
